grafana:
  adminPassword: admin123
  priorityClassName: monitoring
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
    - grafana.local
  nodeSelector:
    kubernetes.io/hostname: t495
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
prometheus:
  prometheusSpec:
    priorityClassName: monitoring
    retention: 7d
    retentionSize: 10GB
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    nodeSelector:
      kubernetes.io/hostname: t495
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    scrapeInterval: 30s
    evaluationInterval: 30s
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
    - prometheus.local
alertmanager:
  alertmanagerSpec:
    priorityClassName: monitoring
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    nodeSelector:
      kubernetes.io/hostname: t495
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
defaultRules:
  create: true
  rules:
    etcd: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
