image:
  tag: "3.0"

startServices: "s3,lambda,dynamodb,sqs,sns,stepfunctions,iam,secretsmanager,cloudformation,logs,events"

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

service:
  type: LoadBalancer
  port: 4566

nodeSelector:
  kubernetes.io/hostname: t495

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

extraEnvVars:
  - name: DEBUG
    value: "1"
  - name: PERSISTENCE
    value: "1"
  # FIXED: Use local executor instead of docker
  - name: LAMBDA_EXECUTOR
    value: "local"  # Changed from "docker"
  # REMOVED: DOCKER_HOST environment variable

# REMOVED: Docker socket volume mounting
# volumes: []
# volumeMounts: []

# Readiness probe
readinessProbe:
  httpGet:
    path: /_localstack/health
    port: 4566
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Liveness probe
livenessProbe:
  httpGet:
    path: /_localstack/health
    port: 4566
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Keep only LoadBalancer services that need external access
