image:
  tag: "3.0"

startServices: "s3,lambda,dynamodb,sqs,sns,stepfunctions,iam,secretsmanager,cloudformation,logs,events"

persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 3Gi

service:
  type: LoadBalancer
  port: 4566

extraEnvVars:
  - name: DEBUG
    value: "1"
  - name: PERSISTENCE
    value: "1"
  - name: LAMBDA_EXECUTOR
    value: "docker"

# Add init job for resource creation
extraResources:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: localstack-init
      namespace: localstack
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: aws-setup
            image: amazon/aws-cli:latest
            env:
            - name: AWS_ENDPOINT_URL
              value: "http://localstack:4566"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            command:
            - /bin/sh
            - -c
            - |
              # Wait for LocalStack
              until aws --endpoint-url=http://localstack:4566 s3 ls; do sleep 10; done
              
              # Create S3 buckets
              aws s3 mb s3://mlflow-artifacts
              aws s3 mb s3://kubeflow-pipelines
              aws s3 mb s3://model-registry
              aws s3 mb s3://datasets
              
              # Create DynamoDB tables
              aws dynamodb create-table \
                --table-name ml-experiments \
                --attribute-definitions AttributeName=id,AttributeType=S \
                --key-schema AttributeName=id,KeyType=HASH \
                --billing-mode PAY_PER_REQUEST
              
              # Create SQS queues
              aws sqs create-queue --queue-name ml-training-queue
              aws sqs create-queue --queue-name model-deployment-queue
              
              echo "LocalStack initialization completed"
