# Prevent pre-upgrade race conditions
preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultReplicaCount: 1
  replicaSoftAntiAffinity: false
  createDefaultDiskLabeledNodes: true
  createDefaultDiskOnLabeledNodes: true
  defaultDataPath: /var/lib/longhorn
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10
  guaranteedEngineManagerCPU: 12
  guaranteedReplicaManagerCPU: 12
  upgradeChecker: false
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/hostname: t495

longhornDriver:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/hostname: t495

longhornUI:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    kubernetes.io/hostname: t495

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Post-install hook to configure node disk
csi:
  kubeletRootDir: /var/lib/kubelet

# Enable metrics
metrics:
  serviceMonitor:
    enabled: true
