defaultSettings:
  defaultReplicaCount: 1
  replicaSoftAntiAffinity: false
  createDefaultDiskLabeledNodes: true
  createDefaultDiskOnLabeledNodes: true
  defaultDataPath: /var/lib/longhorn
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

# CRITICAL: Disable pre-upgrade job
preUpgradeChecker:
  jobEnabled: false

longhornManager:
  tolerations: []
  nodeSelector: {}

longhornDriver:
  tolerations: []
  nodeSelector: {}

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  enabled: false

# Node configuration via Helm extraResources
extraResources:
  - apiVersion: longhorn.io/v1beta2
    kind: Node
    metadata:
      name: t495  # Replace with your actual node name
      namespace: longhorn-system
    spec:
      allowScheduling: true
      evictionRequested: false
      disks:
        default-disk:
          allowScheduling: true
          evictionRequested: false
          path: /var/lib/longhorn
          storageReserved: 21474836480
          tags: []
      tags: []
