mode: standalone
auth:
  rootUser: minio
  rootPassword: minio123
persistence:
  enabled: true
  storageClass: longhorn
  size: 50Gi
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 2Gi
service:
  type: LoadBalancer
consoleService:
  type: LoadBalancer
defaultBuckets: "mlflow,datasets,models"
