mode: standalone

auth:
  rootUser: minio
  rootPassword: minio123

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 50Gi

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m  # Reduced from 500m
    memory: 1Gi  # Reduced from 2Gi

service:
  type: LoadBalancer
  ports:
    api: 9000
    console: 9001

consoleService:
  type: LoadBalancer

defaultBuckets: "mlflow,datasets,models,kubeflow-pipelines"

nodeSelector:
  kubernetes.io/hostname: t495

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring

# Readiness and liveness probes
readinessProbe:
  httpGet:
    path: /minio/health/ready
    port: 9000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /minio/health/live
    port: 9000
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Environment variables for S3 compatibility
environment:
  MINIO_API_CORS_ALLOW_ORIGIN: "*"
  MINIO_BROWSER_REDIRECT_URL: "http://minio-console.local"
