auth:
  postgresPassword: postgrespw
  username: mlflow
  password: mlflowpw
  database: mlflow

primary:
  persistence:
    enabled: true
    storageClass: longhorn
    accessModes: 
      - ReadWriteOnce
    size: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m  # Reduced from 500m
      memory: 1Gi  # Reduced from 2Gi
  nodeSelector:
    kubernetes.io/hostname: t495
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

backup:
  enabled: true
  cronjob:
    schedule: "0 2 * * *"
    storage:
      size: 10Gi
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce

# Readiness probe configuration
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Liveness probe configuration
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
