grafana:
  adminPassword: admin123
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m  # Reduced from 500m
      memory: 512Mi
  service:
    type: LoadBalancer
  nodeSelector:
    kubernetes.io/hostname: t495
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 10GB
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 500m  # Reduced from 1
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    nodeSelector:
      kubernetes.io/hostname: t495
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    additionalScrapeConfigs:
    - job_name: 'localstack'
      static_configs:
      - targets: ['localstack.localstack.svc.cluster.local:4566']
      metrics_path: '/_localstack/health'
      scrape_interval: 30s
    - job_name: 'mlflow'
      static_configs:
      - targets: ['mlflow.mlflow.svc.cluster.local:5000']
      metrics_path: '/metrics'
      scrape_interval: 30s
    - job_name: 'minio'
      static_configs:
      - targets: ['minio.data.svc.cluster.local:9000']
      metrics_path: '/metrics'
      scrape_interval: 30s

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m  # Reduced from 200m
        memory: 256Mi
    nodeSelector:
      kubernetes.io/hostname: t495
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

nodeExporter:
  enabled: true
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

kubeStateMetrics:
  enabled: true

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false
    configReloaders: true
    general: true
    k8s: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    node: true
    nodeExporter: true
    prometheus: true
    prometheusOperator: true
