grafana:
  adminPassword: admin123
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  # Use ClusterIP to avoid port conflicts
  service:
    type: ClusterIP
    port: 80
  nodeSelector:
    kubernetes.io/hostname: t495
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  # Add ingress for external access
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - grafana.local
    path: /
    tls: []
