auth:
  enabled: false
master:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
replica:
  replicaCount: 0
