apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: jupyterhub
  repo: https://hub.jupyter.org/helm-chart/
  version: 3.3.7
  releaseName: jupyterhub
  namespace: jupyter
  valuesFile: values.yaml
