preUpgradeChecker:
  jobEnabled: false
defaultSettings:
  defaultReplicaCount: 1
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 200
  upgradeChecker: false
  defaultDataPath: /var/lib/longhorn
persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
longhornManager:
  priorityClass: infrastructure-critical
  nodeSelector:
    kubernetes.io/hostname: t495
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
