apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-node-config
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: longhorn-node-config
      nodeSelector:
        kubernetes.io/hostname: t495
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
      - name: node-config
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Configuring Longhorn node disk..."
          
          # Wait for Longhorn API to be ready
          until kubectl get crd nodes.longhorn.io; do
            echo "Waiting for Longhorn CRDs..."
            sleep 10
          done
          
          # Wait for Longhorn manager to be ready
          until kubectl get pods -n longhorn-system -l app=longhorn-manager | grep -q Running; do
            echo "Waiting for Longhorn manager..."
            sleep 10
          done
          
          # Label node for Longhorn
          kubectl label node t495 node.longhorn.io/create-default-disk=true --overwrite
          
          # Configure node with proper disk settings
          cat <<EOF | kubectl apply -f -
          apiVersion: longhorn.io/v1beta2
          kind: Node
          metadata:
            name: t495
            namespace: longhorn-system
          spec:
            allowScheduling: true
            evictionRequested: false
            disks:
              default-disk:
                allowScheduling: true
                evictionRequested: false
                path: /var/lib/longhorn
                storageReserved: 21474836480
                tags: []
            tags: []
          EOF
          
          echo "✓ Longhorn node configuration completed"
          
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-node-config
  namespace: longhorn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-node-config
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["longhorn.io"]
  resources: ["nodes"]
  verbs: ["get", "list", "create", "patch", "update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-node-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-node-config
subjects:
- kind: ServiceAccount
  name: longhorn-node-config
  namespace: longhorn-system
