apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: jupyter
  labels:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: localstack
  labels:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    control-plane: kubeflow
    argocd.argoproj.io/sync-wave: "-100"
