deployment:
  replicas: 1
priorityClassName: infrastructure-critical
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.1.240
ports:
  web:
    port: 80
    exposedPort: 80
  websecure:
    port: 443
    exposedPort: 443
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.local`)
nodeSelector:
  kubernetes.io/hostname: t495
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
