apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ml-platform
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: mlflow
        namespace: mlflow
        wave: "20"
      - name: jupyterhub
        namespace: jupyter
        wave: "30"
      - name: localstack
        namespace: localstack
        wave: "25"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/SandipJaiswal/mlops-homelab-gitops
        targetRevision: main
        path: 'platform/ml/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
