apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: prometheus-stack
        namespace: monitoring
        wave: "40"
      - name: loki-stack
        namespace: monitoring
        wave: "50"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/SandipJaiswal/mlops-homelab-gitops
        targetRevision: main
        path: 'monitoring/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
