apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://helm.localstack.cloud
    chart: localstack
    targetRevision: 0.6.17
    helm:
      valueFiles:
        - $values/clusters/homelab/values/localstack-values.yaml
  sources:
    - repoURL: https://helm.localstack.cloud
      chart: localstack
      targetRevision: 0.6.17
    - repoURL: https://github.com/SandipJaiswal/mlops-homelab-gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
