apiVersion: batch/v1
kind: Job
metadata:
  name: localstack-init
  namespace: localstack
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: amazon/aws-cli:latest
        env:
        - name: AWS_ENDPOINT_URL
          value: "http://localstack:4566"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for LocalStack..."
          until curl -f http://localstack:4566/_localstack/health; do
            sleep 10
          done
          
          echo "Creating S3 buckets..."
          aws s3 mb s3://ml-artifacts || true
          aws s3 mb s3://datasets || true
          aws s3 mb s3://models || true
          aws s3 mb s3://kubeflow-pipelines || true
          
          echo "Creating DynamoDB tables..."
          aws dynamodb create-table \
            --table-name ml-experiments \
            --attribute-definitions AttributeName=id,AttributeType=S \
            --key-schema AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST || true
          
          echo "✓ LocalStack initialized"
