image:
  tag: "3.0"
startServices: "s3,lambda,dynamodb,sqs,sns,iam,secretsmanager,stepfunctions"
persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi
priorityClassName: ml-platform
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
service:
  type: ClusterIP
  port: 4566
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
  - host: localstack.local
    paths:
    - path: /
      pathType: Prefix
nodeSelector:
  kubernetes.io/hostname: t495
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
extraEnvVars:
- name: PERSISTENCE
  value: "1"
- name: LAMBDA_EXECUTOR
  value: "local"
- name: DEBUG
  value: "0"
