apiVersion: batch/v1
kind: Job
metadata:
  name: localstack-init
  namespace: localstack
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/hostname: t495
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
      - name: aws-setup
        image: amazon/aws-cli:latest
        env:
        - name: AWS_ENDPOINT_URL
          value: "http://localstack:4566"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for LocalStack to be ready..."
          
          # Wait for LocalStack to be accessible
          until curl -f http://localstack:4566/_localstack/health; do
            echo "Waiting for LocalStack service..."
            sleep 10
          done
          
          echo "LocalStack is ready, initializing resources..."
          
          # Create S3 buckets
          aws s3 mb s3://mlflow-artifacts || echo "Bucket mlflow-artifacts already exists"
          aws s3 mb s3://kubeflow-pipelines || echo "Bucket kubeflow-pipelines already exists"
          aws s3 mb s3://model-registry || echo "Bucket model-registry already exists"
          aws s3 mb s3://datasets || echo "Bucket datasets already exists"
          aws s3 mb s3://lambda-deployments || echo "Bucket lambda-deployments already exists"
          
          # List created buckets
          echo "Created S3 buckets:"
          aws s3 ls
          
          # Create DynamoDB tables
          aws dynamodb create-table \
            --table-name ml-experiments \
            --attribute-definitions AttributeName=id,AttributeType=S \
            --key-schema AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST || echo "Table ml-experiments already exists"
          
          aws dynamodb create-table \
            --table-name ml-models \
            --attribute-definitions AttributeName=model_id,AttributeType=S \
            --key-schema AttributeName=model_id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST || echo "Table ml-models already exists"
          
          # List created tables
          echo "Created DynamoDB tables:"
          aws dynamodb list-tables
          
          # Create SQS queues
          aws sqs create-queue --queue-name ml-training-queue || echo "Queue ml-training-queue already exists"
          aws sqs create-queue --queue-name model-deployment-queue || echo "Queue model-deployment-queue already exists"
          aws sqs create-queue --queue-name data-processing-queue || echo "Queue data-processing-queue already exists"
          
          # List created queues
          echo "Created SQS queues:"
          aws sqs list-queues
          
          # Create SNS topics
          aws sns create-topic --name ml-notifications || echo "Topic ml-notifications already exists"
          aws sns create-topic --name model-alerts || echo "Topic model-alerts already exists"
          
          # List created topics
          echo "Created SNS topics:"
          aws sns list-topics
          
          echo "✓ LocalStack initialization completed successfully"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
