apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: t495
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  disks:
    default-disk:
      allowScheduling: true
      evictionRequested: false
      path: /var/lib/longhorn
      storageReserved: 21474836480  # 20GB reserved
      tags: []
  tags: []
