apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c']
        args:
        - |
          until nc -z postgresql.data.svc.cluster.local 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          echo "PostgreSQL is ready"
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:2.14.1
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_STORE_URI
          value: "postgresql://postgres:postgres@postgresql.data.svc.cluster.local:5432/postgres"
        - name: ARTIFACT_ROOT
          value: "s3://mlflow-artifacts/"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://localstack.localstack.svc.cluster.local:4566"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_S3_ADDRESSING_STYLE
          value: "path"
        command: ["mlflow", "server"]
        args:
        - "--backend-store-uri=$(BACKEND_STORE_URI)"
        - "--default-artifact-root=$(ARTIFACT_ROOT)"
        - "--host=0.0.0.0"
        - "--port=5000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
