---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    name: mlflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:2.14.1
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_STORE_URI
          value: "postgresql://postgres:postgres@postgresql.data.svc.cluster.local:5432/postgres"
        - name: ARTIFACT_ROOT
          value: "s3://mlflow-artifacts/"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://localstack.localstack.svc.cluster.local:4566"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        command: ["mlflow", "server"]
        args:
        - "--backend-store-uri=$(BACKEND_STORE_URI)"
        - "--default-artifact-root=$(ARTIFACT_ROOT)"
        - "--host=0.0.0.0"
        - "--port=5000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
spec:
  type: LoadBalancer
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
