apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/SandipJaiswal/mlops-homelab-gitops
    targetRevision: main
    path: clusters/homelab/manifests/network
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
