apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector }}
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
        - name: traefik
          image: traefik:v2.11.0
          args:
            - --api.dashboard=true
            - --providers.kubernetescrd
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.spec.loadBalancerIP }}
  ports:
    - port: {{ .Values.ports.web.port }}
      targetPort: 80
    - port: {{ .Values.ports.websecure.port }}
      targetPort: 443
  selector:
    app: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  ingressClassName: traefik
  rules:
  - host: traefik.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 8080
