# Assign specific IPs to prevent conflicts
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: data
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
    metallb.universe.tf/loadBalancer-ips: 192.168.1.240
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
    metallb.universe.tf/loadBalancer-ips: 192.168.1.241
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  ports:
  - port: 4566
    targetPort: 4566
    protocol: TCP
    name: localstack
  selector:
    app: localstack
---
# Keep Grafana as ClusterIP (no LoadBalancer needed)
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  type: ClusterIP  # Changed from LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
