apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalancer-priorities
  namespace: metallb-system
data:
  config: |
    # Service priority configuration
    # Higher priority services get IP allocation preference
    services:
      - name: minio
        namespace: data
        priority: 100
      - name: mlflow
        namespace: mlflow
        priority: 90
      - name: localstack
        namespace: localstack
        priority: 80
      - name: prometheus-stack-prometheus
        namespace: monitoring
        priority: 70
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: data
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
    metallb.universe.tf/allow-shared-ip: "false"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240  # Assign specific IP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
    metallb.universe.tf/allow-shared-ip: "false"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241  # Assign specific IP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: mlflow
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
    metallb.universe.tf/allow-shared-ip: "false"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242  # Assign specific IP
  ports:
  - port: 4566
    targetPort: 4566
    protocol: TCP
    name: localstack
  selector:
    app: localstack
