apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: infrastructure-critical
value: 1000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: data-services
value: 900
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ml-platform
value: 800
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubeflow-critical
value: 850
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: monitoring
value: 700
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 100
globalDefault: true
