---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-quota
  namespace: data
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: 4Gi
    limits.cpu: "3"
    limits.memory: 6Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubeflow-quota
  namespace: kubeflow
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "10"
    limits.memory: 15Gi
