apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-quota
  namespace: data
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: 4Gi
    limits.cpu: "3"
    limits.memory: 6Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubeflow-quota
  namespace: kubeflow
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "10"
    limits.memory: 15Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlflow-quota
  namespace: mlflow
spec:
  hard:
    requests.cpu: "300m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: jupyter-quota
  namespace: jupyter
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: localstack-quota
  namespace: localstack
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 3Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
