name: Validate GitOps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Kubernetes tools
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/
    
    - name: Validate Kustomizations
      run: |
        find . -name "kustomization.yaml" | while read -r file; do
          dir=$(dirname "$file")
          echo "Validating: $dir"
          kustomize build "$dir" > /dev/null || exit 1
        done
    
    - name: Basic YAML validation
      run: |
        # Basic YAML structure checks
        find . -name "*.yaml" -o -name "*.yml" | while read -r file; do
          if ! grep -q -E "^(---|[a-zA-Z])" "$file"; then
            echo "Error: Invalid YAML structure in $file"
            exit 1
          fi
        done
    
    - name: Security scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
